apiVersion: v1
kind: Secret
metadata:
    name: mail-secret
    namespace: wikiwars
data:
    mail_password: ENC[AES256_GCM,data:Q8TbwHawlA47RkYKbGTWbw==,iv:Fel9Yj5V0UAbpV73dUfhKlbbx1q0gHhvIogZaW0ItUQ=,tag:dX/M4rqv+fYMpPhNepdvFA==,type:str]
sops:
    age:
        - recipient: age1gr775xu7s2fkepm0amxt3rpk5y09785e9245fsvtr920xwm40ylshh9r4d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNUHFiSzRoWlNYM0hXUW8z
            a0JMejNxYjNzMEgxUmZOU2lmYVZkT096M0YwCmJoTnk1NVNVSGNnZWR2biszUE9L
            VTFGZUdxZmVia2xWdGdGbURqa1NXRGMKLS0tIDNrQlFGWnM4TjFxM3BXcEsyTnhZ
            Tmk1MStvZGh0aGxYclhEV0VUSVluSFEKZXEs/Fnyaubxfog/JdCSaicvc/f7Gsxf
            bh4QfgkXhBN4PL7TaXphJnok9jv0zKB/foUN6GdiDtOZOV/Fwe1HwQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-06T15:08:12Z"
    mac: ENC[AES256_GCM,data:IwNcsmYlcKnSA+DKLModtzlNDyo1MvDmxSJ5cCYtJXx5J+W4QKoc1qQKmdN+gySc/ZvoX4S7npciqryPSFBLLqOs3hgvK3/PfHJInLaH4vcVCyQRMX/bOgO5zmvjs1e6nuhHkK1ihrcGpCIHmVUY7T8BVl1/tMpXGPxJSSi3Mwk=,iv:D/1b4zqvhl3i5b+5bLZz0Y9Q+6pv9JTkigjDbeigva0=,tag:f98lrFqMIYrR9xcFAymlQg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
