apiVersion: v1
kind: Secret
metadata:
    name: database-secret
    namespace: wikiwars
data:
    postgres_password: ENC[AES256_GCM,data:XcBcfygQNC9pQbdyIlCj2y8Bzfll2alpHtqkcEuLN0Y=,iv:WZ3RBYVr7YNU4Yatrhx773aci/P31lwQv9/m+WcJc7o=,tag:5V281DVRj4LcIwcGN3xHKw==,type:str]
sops:
    age:
        - recipient: age1gr775xu7s2fkepm0amxt3rpk5y09785e9245fsvtr920xwm40ylshh9r4d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFUlZScHAvMWtXR2YwdlFT
            K2VjWGdLWGdiTjFIV2M4bE5RSHJ4M0IwN0NrCkI0K3pWNWNBcWFTODVkTTdSdW9H
            cmNUSnVEVGMzbzczVzIzb2U4RDJIU1UKLS0tIFBDNkx0bGQ5cndFeE8rM3E4Skpn
            K25oWjVWUTc1aXQ5QkZLVjhGUVdIOHcKZBmqjyJ0Vc824QbGt6i53dOSot/ELC6z
            hhiAYPoHSK+mbNCRa449m1Pre7TxiR9RZRfl+UuWovnSOXA8ADdYMA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-06T15:08:12Z"
    mac: ENC[AES256_GCM,data:57vTr2PnIlWmSDfNrbEoWRbqQ0c90HOX8BF5Tuy85E2etP7W5CwRhUKG0xQ1jyuXeebGfcixiJiXFRedHFBZP1NIepkIYyIQ4chiRRaStnIvMxUiZ9nv5lCHux8KllS7sKKjyHjyImtQDgHtEEq+q+7ZMoqjQEhrFUwNB4F3ews=,iv:1l6B/ZPz1g8f0lREDG6gfhszWY/xMUAaxu5dciQ328w=,tag:/+kFugJnymIGCmGDeWAObQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
