apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend
  namespace: wikiwars
  labels:
    app: backend
  annotations:
    # âœ… Configuration cert-manager pour Let's Encrypt
    cert-manager.io/cluster-issuer: letsencrypt
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
spec:
  tls:
    - hosts:
        - api.wiki-wars.fr
      secretName: backend-letsencrypt
  rules:
    - host: api.wiki-wars.fr
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 5000