apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: front
  namespace: wikiwars
  labels:
    app: front
  annotations:
    # âœ… Configuration cert-manager pour Let's Encrypt
    cert-manager.io/cluster-issuer: letsencrypt
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
spec:
  tls:
    - hosts:
        - wiki-wars.fr
      secretName: front-letsencrypt
  rules:
    - host: wiki-wars.fr
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: front
                port:
                  number: 80